[build]
builder = "NIXPACKS"
buildCommand = buildCommand = "pnpm install --no-frozen-lockfile && PORT=8080 BASE_PATH=/ pnpm --filter @workspace/selfbeat run build"

[deploy]
startCommand = "node deploy/index.mjs"
healthcheckPath = "/api/healthz"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
